sudo: required
language: go
go:
- 1.10.1
services:
  - docker
script:
  - make
  - make test
  - export SHORT_SHA=${TRAVIS_COMMIT:6}
  - make container TAG=$SHORT_SHA
  - ./push-image.sh
notifications:
  email: false
